import Head from 'next/head'
import SideBar from '../../components/SideBar'
import Image from 'next/image'
import defaultImg from '../../public/img_forest.jpg'
import { GetStaticPaths, GetStaticProps } from 'next'
import { PostData } from '../../components/Posts'



const publicFolder = "http://localhost:4000/images/";

const SinglePost: React.FC<PostData> = (props) => {

    return (
        <div className='pt-8  p-2'>
            <Head>
                <title>{props._id}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex flex-wrap gap-5 justify-center'>
                <div className='w-full lg:w-3/4 flex flex-col gap-8'>
                    {props.photo !== '' ?
                        <Image src={publicFolder.concat(props.photo)} className='object-cover' alt={props.title} height={200} width={200} /> :
                        <Image src={defaultImg} className='object-cover' alt="img" />}
                    <h2 className='font-bold text-xl text-center'>Title</h2>
                    <div className='flex justify-between'>
                        <span>Author:han</span>
                        <span>2 minutes ago</span>
                    </div>
                    <p>
                        text text text text text text text text text text text text text text
                        text text text text text text text text text text text text text text
                        text text text text text text text text text text text text text text
                        text text text text text text text text text text text text text text
                        text text text text text text text text text text text text text text
                        text text text text text text text text text text text text text text
                    </p>
                </div>
                <SideBar />
            </div>

        </div>
    )
}

export const getStaticPaths: GetStaticPaths = async () => {
    const res = await fetch('http://localhost:4000/api/posts')
    const posts: [PostData] = await res.json();

    const paths = posts.map((post) => ({
        params: { id: post._id },
    }))

    return {
        paths,
        fallback: 'blocking'
    }

}


export const getStaticProps: GetStaticProps = async (context) => {
    const post: PostData = await fetch(`hhttp://localhost:4000/api/post/${context.params!.id}`).then(res => res.json());

    return {
        props: {
            post
        },
        revalidate: 20
    }

}

export default SinglePost;