import type { NextPage } from 'next'
import Head from 'next/head'
import SideBar from '../components/SideBar'
import Posts from '../components/Posts'

const Home: NextPage = () => {
  return (
    <div className='pt-8  p-2'>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-wrap gap-5 justify-center'>
        <Posts />
        <SideBar />
      </div>



    </div>
  )
}

export default Home
