import type { NextPage } from 'next'
import Head from 'next/head'
import SideBar from '../components/SideBar'
import Image from 'next/image'
import img from '../public/img_forest.jpg'


const SinglePost: NextPage = () => {
  return (
    <div className='pt-8  p-2'>
      <Head>
        <title>Single Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-wrap gap-5 justify-center'>
        <div className='w-full lg:w-3/4 flex flex-col gap-8'>
          <Image src={img} alt="img" className="object-none" height={300} />
          <h2 className='font-bold text-xl text-center'>Title</h2>
          <div className='flex justify-between'>
            <span>Author:han</span>
            <span>2 minutes ago</span>
          </div>
          <p>
            text text text text text text text text text text text text text text
            text text text text text text text text text text text text text text
            text text text text text text text text text text text text text text
            text text text text text text text text text text text text text text
            text text text text text text text text text text text text text text
            text text text text text text text text text text text text text text
          </p>
        </div>
        <SideBar />
      </div>



    </div>
  )
}

export default SinglePost;